[package]
name = "lib-servers"
version = "0.0.1"
authors = ["seb-odessa <seb@ukr.net>"]
license = "MIT OR Apache-2.0"

[dependencies]
rand = "*"
log = "*"
env_logger = "*"

[lib]
name = "lib"
path = "src/lib/lib.rs"
